e_front: bundle exec ruby server.rb front -c ./config/grass.rb -p 4000 -e ${ENV:-development} -sv
e_api: bundle exec ruby server.rb api -c ./config/grass.rb -p 4001 -e ${ENV:-development} -sv
haproxy: haproxy -f ./haproxy.cfg